# 基础配置
CONFIG_GPIO=y
CONFIG_MAIN_THREAD_PRIORITY=7
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# 日志配置
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y

# ARES 通信库
CONFIG_ARES=y
CONFIG_ARES_COMM_LIB=y

# 电机驱动支持
CONFIG_MOTOR=y
CONFIG_MOTOR_DM=y
CONFIG_MOTOR_RS=y
CONFIG_MOTOR_DJI=y

# CAN总线支持
CONFIG_CAN=y
CONFIG_CAN_INIT_PRIORITY=80

# 暂时关闭非 USB 串口，避免反馈串口未接入时影响电机 bring-up。
# CONFIG_SERIAL=n
# CONFIG_CONSOLE=n
# CONFIG_UART_CONSOLE=n

# PID控制器支持
CONFIG_PID=y

# USB 控制接口
CONFIG_DUAL_PROPOSE_PROTOCOL=y
CONFIG_USB_BULK_INTERFACE=y
CONFIG_UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED=n
CONFIG_USBD_MAX_SPEED_FULL=y
CONFIG_NET_BUF=y

# UART 调试接口
CONFIG_UART_INTERFACE=y
CONFIG_ARES_UART_THREAD_STACK_SIZE=1024

# 协议支持
CONFIG_ARES_PLOTTER_PROTOCOL=y
CONFIG_ARESPLOT_FREQ=1000
