# Copyright (c) 2021 Nordic Semiconductor ASA
# Copyright (c) 2025 ttwards @ SUSTech
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://www.github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      # Pinned to the Zephyr commit validated by the sample build matrix.
      revision: 6085aadeb337f27ee7411fa2ecbe8cf49164e360
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - cmsis_6
          - cmsis-dsp
          - hal_st
          - hal_stm32
          - mcuboot
          - segger
