

CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_DSP_CONTROLLER=y
CONFIG_CMSIS_DSP_FASTMATH=y

CONFIG_MOTOR=y
CONFIG_MOTOR_COMMON=y
CONFIG_MOTOR_DM=y
CONFIG_MOTOR_RS=y
CONFIG_MOTOR_VESC=y
CONFIG_MOTOR_LK=y
CONFIG_MOTOR_LOG_LEVEL=4
CONFIG_CAN=y
CONFIG_MOTOR_INIT_PRIORITY=90
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_ARES=y
CONFIG_ARES_SBUS=y
CONFIG_EKF_LIB=n
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_ASYNC_API=y
CONFIG_NOCACHE_MEMORY=y
CONFIG_SENSOR=y
CONFIG_BMI08X=n
CONFIG_WIT_HWT906=n

CONFIG_AUTO_PROBE_GYRO_BIAS=n

CONFIG_CHASSIS=y
CONFIG_PID=y

CONFIG_DUAL_PROPOSE_PROTOCOL=y
CONFIG_USB_BULK_INTERFACE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED=n
CONFIG_USBD_MAX_SPEED_FULL=y

# CONFIG_SEGGER_SYSTEMVIEW=y

# CONFIG_TRACING_SYSCALL=n

CONFIG_UDC_DRIVER_LOG_LEVEL_INF=y
CONFIG_USBD_LOG_LEVEL_INF=y
CONFIG_USBD_CDC_ACM_LOG_LEVEL_WRN=y

CONFIG_CBPRINTF_FP_SUPPORT=y
