# Gaoqing motor demo common configuration.

CONFIG_MAIN_THREAD_PRIORITY=7
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_MOTOR=y
CONFIG_MOTOR_GQ=y

CONFIG_CAN=y
CONFIG_CAN_INIT_PRIORITY=80
