# ARES MQTT-like protocol over USB Bulk

CONFIG_USB_BULK_INTERFACE=y
CONFIG_ARES_MQTTLITE_PROTOCOL=y
CONFIG_NET_BUF=y

CONFIG_MAIN_THREAD_PRIORITY=10

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_UDC_DRIVER_LOG_LEVEL_INF=y
CONFIG_USBD_LOG_LEVEL_INF=y
