# 开启 GPIO 驱动支持
CONFIG_GPIO=y

# 开启控制台打印 (用于 printk)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_ARES=y
CONFIG_DUAL_PROPOSE_PROTOCOL=y
# CONFIG_UART_INTERFACE=y
CONFIG_USB_BULK_INTERFACE=y

CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=n
CONFIG_USBD_LOG_LEVEL_WRN=not

