# dm_mc02 uses USART10 as the debug console, so keep this sample focused on USB bulk.
CONFIG_UART_INTERFACE=n

CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG_BACKEND_UART=y

CONFIG_SENSOR=n
CONFIG_BMI08X=n
