# GPIO 配置
CONFIG_GPIO=y

# ARES 通信库
CONFIG_ARES=y
CONFIG_UART_INTERFACE=y
CONFIG_DUAL_PROPOSE_PROTOCOL=y

# UART 接口线程栈大小
CONFIG_ARES_UART_THREAD_STACK_SIZE=1024

# 日志配置
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y

# 电机驱动支持
CONFIG_MOTOR=y
CONFIG_MOTOR_RS=y
CONFIG_MOTOR_DM=y

# CAN总线支持
CONFIG_CAN=y
CONFIG_CAN_INIT_PRIORITY=80

# PID控制器支持
CONFIG_PID=y

# 主线程优先级
CONFIG_MAIN_THREAD_PRIORITY=7
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
