CONFIG_MAIN_THREAD_PRIORITY=7
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_LOG=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_CAN=y
CONFIG_CAN_INIT_PRIORITY=80

CONFIG_PID=y
CONFIG_MOTOR=y
CONFIG_MOTOR_LK_TEST=y
CONFIG_MOTOR_LOG_LEVEL=4
